### ISSUE TITLE
Finetuning / Distillation for Mixtral?

### ISSUE THREAD

**Issue by LorrinWWW** [UNITES-Lab/MC-SMoE#1]
Thank you for sharing the work! Congratulations!
Do you have plan to release the fine-tuning / distillation code for mixtral? Really appreciate it!

**Comment by pingzhili** [comment]
Thank you for your interest! This is an important suggestion - to evaluate the final performance of MC-SMoE on Mixtral.

We haven't tried it yet, as distillation on large models like Mistral can be very costly in terms of time/memory. If you encounter any specific code issues, feel free to post them here so we can work together to solve them :)
